version: 1.0.0.{build}
image: Visual Studio 2017

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/8cf3160c9516ef1f4effc825c0a44acc918a0b5a/appveyor-build-info.ps'))

build_script:
- cmd: build.cmd

test_script:
- tests\CodeCoverage\CodeCoverage.cmd

artifacts:
- path: artifacts\bin\ImageSharp\**\*.nupkg

deploy:
    # MyGet Deployment for builds & releases
 - provider: NuGet
   server: https://www.myget.org/F/imagesharp/api/v2/package
   symbol_server: https://www.myget.org/F/imagesharp/api/v2/package # https://nuget.symbolsource.org/MyGet/imagesharp
   api_key:
     secure: fz0rUrt3B1HczUC1ZehwVsrFSWX9WZGDQoueDztLte9/+yQG+BBU7UrO+coE8lUf
   artifact: /.*\.nupkg/
   on:
     branch: master
